project:
  type: website

website:
  title: Public
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yoursdearboy
      - icon: twitter
        href: https://twitter.com/prlunestia

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
